### PR TITLE
adding optional Custom cssClass

### PR DESCRIPTION
**Pull request by IbrahimHd**
Increasing the flexibility of the directive thru supporting custom **cssClass**

### CODE REVIEW

**Comment by IbrahimHd** [comment]
Thank you Gleb for the merge!
could you plz arrange for new release?

**Comment by g1eb** [comment]
Yup, I've added this to v0.1.23 👍

**Comment by IbrahimHd** [comment]
Hi Gleb,

As the CSS style structure, child classes depend on the 'display' class, like this ( .display  .date ).
This means that if the predefined 'display' class overridden by a custom class, all **descendant** classes will be OFF.
My suggestion is to keep the predefined 'display' class and allow for a custom class for style override in order to keep the other inherited classes work as expected.
Changes need to be done:
`ng-class="{'active': !!selected, 'display': !cssClass, '{{cssClass}}': !!cssClass}"`
becomes:
```
class="display"
ng-class="{'active': !!selected, '{{cssClass}}': !!cssClass}"

```
I hope I'm clear in my point.
Thnx

**Comment by g1eb** [comment]
Oh yea, I agree with you! Fixed this in the latest version 😃 

v0.1.24

**Pull request merged**
